bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pediatric_logo_light.png
    - docs/images/nf-core-pediatric_logo_light.png
    - docs/images/nf-core-pediatric_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - assets/FS_BN_GL_SF_utils/**
    - assets/templates/**
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pediatric_logo_light.png
    - docs/images/nf-core-pediatric_logo_light.png
    - docs/images/nf-core-pediatric_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Anthony Gagnon
  description: nf-pediatric is a neuroimaging pipeline to process pediatric MRI data
    (dMRI, and sMRI) ranging from 0-18 years old.
  force: false
  is_nfcore: false
  name: pediatric
  org: nf
  outdir: .
  skip_features:
    - igenomes
  version: 1.0dev
update: null
