---
name: "image_convert"
description: |
  Small utility module to perform data type conversion on images. The new
  datatype has to be specified using the task.ext.datatype parameter, otherwise,
  the module will fail.
keywords:
  - image
  - convert
  - datatype
tools:
  - "MRtrix3":
      description: "MRtrix3 is a software package for various types of diffusion imaging data, including diffusion-weighted, diffusion-tensor, and q-ball imaging."
      homepage: "https://www.mrtrix.org/"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - image:
      type: file
      description: Image to convert.
      pattern: "*.nii.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - image:
      type: file
      description: Image converted into the specified datatype.
      pattern: "*_converted.nii.gz"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
